  
[context.production]
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "12.18.2", TO_DZIALA = "wtf" }

[context.staging]
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "12.18.2", CONTENT_VERSION = "draft" }

[[plugins]]
package = "../../plugins/netlify-plugin-hello-world"